export interface ConfigResponse {
    COLLECTORS_INTERVAL: number;
    DEFAULT_BUFFER_CONTINOUS_COLLECTORS: number;
    SDK_ENABLED: boolean;
  }

  /*{ COLLECTORS_INTERVAL: 60000, DEFAULT_BUFFER_CONTINOUS_COLLECTORS: 10, SDK_ENABLED: true }*/